spring:
  application:
    name: springbootService
server:
  port: 6001
eureka:
  client:
    service-url:
      defaultZone: http://localhost:5000/eureka/
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/zpp
    username: root
    password: 123456

mybatis:
  type-aliases-package: zpp.entity
   mapperLocations: classpath:mybatis/*.xml
